spring:
  config:
    import:
      - optional:file:./deploy/.env[.properties]
      - optional:file:../deploy/.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:${EVENTFLOW_DB_PORT:3306}/eventflow?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${EVENTFLOW_DB_USERNAME:eventflow}
    password: ${EVENTFLOW_DB_PASSWORD}
  data:
    redis:
      host: ${EVENTFLOW_REDIS_HOST:localhost}
      port: ${EVENTFLOW_REDIS_PORT:6379}
  rabbitmq:
    host: ${EVENTFLOW_RABBITMQ_HOST:localhost}
    port: ${EVENTFLOW_RABBITMQ_PORT:5672}
    username: ${EVENTFLOW_RABBITMQ_USERNAME:eventflow}
    password: ${EVENTFLOW_RABBITMQ_PASSWORD}
